export const ENV = {
  DB_SCHEMA: process.env.DB_SCHEMA,
  PORT: process.env.PORT,
  DATABASE_URL: process.env.DATABASE_URL,
  JWT_SECRET: process.env.JWT_SECRET,

  RELOADLY_CLIENT_ID: process.env.RELOADLY_CLIENT_ID,
  RELOADLY_CLIENT_SECRET: process.env.RELOADLY_CLIENT_SECRET,

  DING_API_KEY: process.env.DING_API_KEY,

  PAYSTACK_SECRET_KEY: process.env.PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY: process.env.PAYSTACK_PUBLIC_KEY,
  PAYSTACK_BASE_URL: process.env.PAYSTACK_BASE_URL,
};